# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(599, 489)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 91, 41))
        self.label.setObjectName("label")
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setGeometry(QtCore.QRect(0, 30, 111, 23))
        self.openButton.setObjectName("openButton")
        self.size = QtWidgets.QSpinBox(self.centralwidget)
        self.size.setGeometry(QtCore.QRect(90, 60, 71, 22))
        self.size.setMinimum(1)
        self.size.setMaximum(40)
        self.size.setProperty("value", 10)
        self.size.setObjectName("size")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 60, 81, 16))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 130, 601, 321))
        self.textEdit.setObjectName("textEdit")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(0, 460, 75, 23))
        self.saveButton.setObjectName("saveButton")
        self.setButton = QtWidgets.QPushButton(self.centralwidget)
        self.setButton.setGeometry(QtCore.QRect(170, 60, 75, 23))
        self.setButton.setObjectName("setButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 90, 47, 13))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 90, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Редактор"))
        self.openButton.setText(_translate("MainWindow", "Открыть файл"))
        self.label_2.setText(_translate("MainWindow", "Размер текста"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить"))
        self.setButton.setText(_translate("MainWindow", "Применить"))
        self.label_3.setText(_translate("MainWindow", "Шрифт"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Arial"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Times New Roman"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Calibri"))
