# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tables_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(597, 340)
        self.closeButton = QtWidgets.QPushButton(Form)
        self.closeButton.setGeometry(QtCore.QRect(0, 0, 81, 23))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 591, 241))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.tablesList = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.tablesList.setObjectName("tablesList")
        self.verticalLayout_4.addWidget(self.tablesList)
        self.addBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addBtn.setObjectName("addBtn")
        self.verticalLayout_4.addWidget(self.addBtn)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.query = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.query.setObjectName("query")
        self.verticalLayout_3.addWidget(self.query)
        self.execBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.execBtn.setObjectName("execBtn")
        self.verticalLayout_3.addWidget(self.execBtn)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.closeButton.setText(_translate("Form", "Отключиться"))
        self.label_2.setText(_translate("Form", "Список таблиц"))
        self.addBtn.setText(_translate("Form", "Создать новую таблицу"))
        self.label.setText(_translate("Form", "SQL запрос"))
        self.execBtn.setText(_translate("Form", "Выполнить"))
