# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(597, 590)
        self.returnButton = QtWidgets.QPushButton(Form)
        self.returnButton.setGeometry(QtCore.QRect(0, 0, 151, 23))
        self.returnButton.setObjectName("returnButton")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(0, 20, 591, 551))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.saveBtn = QtWidgets.QPushButton(Form)
        self.saveBtn.setGeometry(QtCore.QRect(150, 570, 151, 23))
        self.saveBtn.setObjectName("saveBtn")
        self.dropBtn = QtWidgets.QPushButton(Form)
        self.dropBtn.setGeometry(QtCore.QRect(450, 570, 141, 23))
        self.dropBtn.setObjectName("dropBtn")
        self.deleteBtn = QtWidgets.QPushButton(Form)
        self.deleteBtn.setGeometry(QtCore.QRect(300, 570, 151, 23))
        self.deleteBtn.setObjectName("deleteBtn")
        self.addBtn = QtWidgets.QPushButton(Form)
        self.addBtn.setGeometry(QtCore.QRect(0, 570, 151, 23))
        self.addBtn.setObjectName("addBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.returnButton.setText(_translate("Form", "Вернуться к списку таблиц"))
        self.saveBtn.setText(_translate("Form", "Сохранить изменения"))
        self.dropBtn.setText(_translate("Form", "Удалить таблицу"))
        self.deleteBtn.setText(_translate("Form", "Отчистить таблицу"))
        self.addBtn.setText(_translate("Form", "Добавить запись"))
