# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(599, 408)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 9, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 13, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 12, 0, 1, 1)
        self.mailText = QtWidgets.QTextEdit(self.centralwidget)
        self.mailText.setObjectName("mailText")
        self.gridLayout.addWidget(self.mailText, 12, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.from_addr = QtWidgets.QLineEdit(self.centralwidget)
        self.from_addr.setObjectName("from_addr")
        self.gridLayout.addWidget(self.from_addr, 1, 2, 1, 1)
        self.file_button = QtWidgets.QPushButton(self.centralwidget)
        self.file_button.setObjectName("file_button")
        self.gridLayout.addWidget(self.file_button, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setObjectName("email")
        self.gridLayout.addWidget(self.email, 7, 2, 1, 1)
        self.subject = QtWidgets.QLineEdit(self.centralwidget)
        self.subject.setObjectName("subject")
        self.gridLayout.addWidget(self.subject, 9, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.files_widjet = QtWidgets.QListWidget(self.centralwidget)
        self.files_widjet.setObjectName("files_widjet")
        self.gridLayout.addWidget(self.files_widjet, 6, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Адрес получателя"))
        self.label_2.setText(_translate("MainWindow", "Тема"))
        self.pushButton.setText(_translate("MainWindow", "Отправить"))
        self.label_3.setText(_translate("MainWindow", "Текст отправки"))
        self.label_5.setText(_translate("MainWindow", "Адрес отправителя"))
        self.comboBox.setItemText(0, _translate("MainWindow", "yandex"))
        self.comboBox.setItemText(1, _translate("MainWindow", "mail"))
        self.comboBox.setItemText(2, _translate("MainWindow", "gmail"))
        self.label_7.setText(_translate("MainWindow", "Выбрать файл"))
        self.label_6.setText(_translate("MainWindow", "Пароль"))
        self.file_button.setText(_translate("MainWindow", "Открыть"))
        self.label_8.setText(_translate("MainWindow", "Список файлов"))
        self.label_4.setText(_translate("MainWindow", "Сервер"))
